/**
 * Merge the extracted Storm 4 motion tables (public/assets/prm/<code>.json) with the clip lengths of
 * the exported GLBs into src/combat/PrmData.ts, keeping only the attack / skill entries whose clip
 * actually exists in the GLB. Frames are converted from the game's 30 fps authoring to the engine's
 * 60 Hz simulation.
 *   node tools/scripts/gen_prm_ts.cjs 2nrt 2ssk ...
 */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..', '..');
const codes = process.argv.slice(2);
const KEEP = /^PL_ANM_(ATK|SKL01_ACT|SKL01_DEMO|SKILL_1_DEMO|PRJ_LAND|PRJ_AIR|SPSKILL_1_DEMO|NUT|RUN1|JMP0|JMP1|DSH_)/;
const out = {};
for (const code of codes) {
  // Clip lengths from the character's GLB plus its awakened-form GLB (Naruto → 2nrv, Sasuke → 2ssv).
  const AW = { '2nrt': '2nrv', '2ssk': '2ssv' };
  const clips = {};
  for (const g of [code, AW[code]].filter(Boolean)) {
    const gp = path.join(root, 'public/assets', `${g}.glb`);
    if (!fs.existsSync(gp)) continue;
    const glb = fs.readFileSync(gp);
    const len = glb.readUInt32LE(12);
    const j = JSON.parse(glb.slice(20, 20 + len).toString());
    for (const a of j.animations) {
      let mx = 0;
      for (const s of a.samplers) { const ac = j.accessors[s.input]; if (ac.max && ac.max[0] > mx) mx = ac.max[0]; }
      clips[a.name] = Math.max(2, Math.round(mx * 60));
    }
  }
  const prm = JSON.parse(fs.readFileSync(path.join(root, 'public/assets/prm', `${code}.json`), 'utf8'));
  const entries = [];
  for (const e of prm.entries) {
    if (!KEEP.test(e.anm)) continue;
    if (!clips[e.clip]) continue;
    entries.push({
      anm: e.anm.replace('PL_ANM_', ''),
      clip: e.clip,
      frames: clips[e.clip],
      hits: e.hits.map((h) => ({ bone: h.bone, dmg: h.dmgId.replace('DAMAGE_ID_', ''), order: h.order, start: h.start * 2, damage: h.damage, radius: h.radius, power: h.power })),
    });
  }
  out[code] = { entries };
  console.log(code, entries.length, 'entries', entries.map((e) => e.anm).join(' '));
}
const ts = `/**
 * PrmData.ts — GENERATED by tools/scripts/gen_prm_ts.cjs from the Storm 4 character parameter
 * tables (data/spc/<code>prm.bin.xfbin, "mot" table) and the exported GLB clip lengths.
 * Frames are 60 Hz (the game authors at 30 fps). Do not edit by hand.
 */
export interface PrmHit { bone: string; dmg: string; order: number; start: number; damage: number; radius: number; power: number; }
export interface PrmEntry { anm: string; clip: string; frames: number; hits: PrmHit[]; }
export const PRM: Record<string, { entries: PrmEntry[] }> = ${JSON.stringify(out)};
`;
fs.writeFileSync(path.join(root, 'src/combat/PrmData.ts'), ts);
console.log('wrote src/combat/PrmData.ts');
